language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
sudo: false
before_install:
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm install -g npm@1.2.8000"
script:
  - "npm run-script test-ci"
after_script:
  - "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
