environment:
  matrix:
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
install:
  - ps: Install-Product node $env:nodejs_version
  - IF "%nodejs_version%" == "0.8" npm install -g npm@1.2.8000
  - SET PATH=%APPDATA%\npm;%PATH%
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-ci
version: "{build}"
